"""Generate deterministic CORDIC constants for the Fixed64 Q32.32 trig library.
Output is C#-ready long literals. Run once; embed the result. No runtime System.Math."""
import math

FRAC = 32
SCALE = 1 << FRAC
N = 32  # iterations (one bit of accuracy per iteration; matches 32 fractional bits)


def q(x):
    return round(x * SCALE)


# atan(2^-i) for i = 0..N-1, in Q32.32
atans = [q(math.atan(2.0 ** -i)) for i in range(N)]

# CORDIC gain An = prod sqrt(1 + 2^-2i); we pre-load x with 1/An so output is unscaled.
an = 1.0
for i in range(N):
    an *= math.sqrt(1.0 + 2.0 ** (-2 * i))
k_inv = q(1.0 / an)

print(f"// Generated by gen_cordic.py — {N} iterations, Q{64-FRAC}.{FRAC}. Do not hand-edit.")
print(f"internal const int Iterations = {N};")
print(f"internal const long CordicGainInverse = {k_inv}L; // 1/An = {1.0/an:.17f}")
print()
print("internal static readonly long[] AtanTable =")
print("{")
for i in range(N):
    print(f"    {atans[i]}L, // atan(2^-{i}) = {math.atan(2.0**-i):.17f}")
print("};")
print()
# Angle constants in Q32.32
print(f"public static readonly Fixed64 Pi = Fixed64.FromRaw({q(math.pi)}L);      // {math.pi:.17f}")
print(f"public static readonly Fixed64 TwoPi = Fixed64.FromRaw({q(2*math.pi)}L);   // {2*math.pi:.17f}")
print(f"public static readonly Fixed64 HalfPi = Fixed64.FromRaw({q(math.pi/2)}L);  // {math.pi/2:.17f}")
print()
# Sanity: convergence range must exceed pi/2
conv = sum(math.atan(2.0**-i) for i in range(N))
print(f"// convergence range = {conv:.6f} rad (must exceed pi/2 = {math.pi/2:.6f})")
