namespace Sim.Core.Numerics;

/// <summary>
/// Deterministic fixed-point trigonometry for <see cref="Fixed64"/> (Q32.32 radians), built on
/// CORDIC — no <c>System.Math</c>, no transcendentals (roadmap §2.5). Every operation is integer
/// shifts, adds, and table lookups, so results are byte-identical across Windows and Linux.
///
/// <para>This is the library Kepler's-equation and the §2.2 reception root-find stand on. Scope is
/// deliberately <b>sin / cos / atan2</b> only — the trio those consumers need. tan/exp/pow are
/// deferred until a later phase actually requires them.</para>
///
/// <para>Constants (iteration count, gain, atan table) are generated by <c>gen_cordic.py</c> and
/// embedded; they are not hand-edited. 32 iterations give one bit of accuracy each, matching the
/// 32 fractional bits of Q32.32.</para>
/// </summary>
public static class Trig
{
    // --- Angle constants (Q32.32 radians) ---

    /// <summary>π.</summary>
    public static readonly Fixed64 Pi = Fixed64.FromRaw(13493037705L);

    /// <summary>2π.</summary>
    public static readonly Fixed64 TwoPi = Fixed64.FromRaw(26986075409L);

    /// <summary>π/2.</summary>
    public static readonly Fixed64 HalfPi = Fixed64.FromRaw(6746518852L);

    private const long PiRaw = 13493037705L;
    private const long TwoPiRaw = 26986075409L;
    private const long HalfPiRaw = 6746518852L;

    // --- Generated CORDIC constants (gen_cordic.py, 32 iterations, Q32.32) ---

    private const int Iterations = 32;
    private const long CordicGainInverse = 2608131496L; // 1/An = 0.60725293500888133

    private static readonly long[] AtanTable =
    {
        3373259426L, 1991351318L, 1052175346L, 534100635L, 268086748L, 134174063L,
        67103403L, 33553749L, 16777131L, 8388597L, 4194303L, 2097152L,
        1048576L, 524288L, 262144L, 131072L, 65536L, 32768L,
        16384L, 8192L, 4096L, 2048L, 1024L, 512L,
        256L, 128L, 64L, 32L, 16L, 8L, 4L, 2L,
    };

    /// <summary>Sine of an angle in radians.</summary>
    public static Fixed64 Sin(Fixed64 radians) => SinCos(radians).Sin;

    /// <summary>Cosine of an angle in radians.</summary>
    public static Fixed64 Cos(Fixed64 radians) => SinCos(radians).Cos;

    /// <summary>
    /// Sine and cosine together — CORDIC produces both from one sweep, so ask for both when you
    /// need both (Kepler does).
    /// </summary>
    public static (Fixed64 Sin, Fixed64 Cos) SinCos(Fixed64 radians)
    {
        // Reduce to (-π, π], then fold into CORDIC's convergent range [-π/2, π/2].
        long z = ReduceToPi(radians.Raw);
        bool negate = false;
        if (z > HalfPiRaw)
        {
            z -= PiRaw;
            negate = true;
        }
        else if (z < -HalfPiRaw)
        {
            z += PiRaw;
            negate = true;
        }

        // Rotation mode: x preloaded with 1/An so the output needs no post-scaling.
        long x = CordicGainInverse;
        long y = 0;
        for (int i = 0; i < Iterations; i++)
        {
            long dx = x >> i;
            long dy = y >> i;
            if (z >= 0)
            {
                x -= dy;
                y += dx;
                z -= AtanTable[i];
            }
            else
            {
                x += dy;
                y -= dx;
                z += AtanTable[i];
            }
        }

        if (negate)
        {
            x = -x;
            y = -y;
        }

        return (Fixed64.FromRaw(y), Fixed64.FromRaw(x));
    }

    /// <summary>
    /// Four-quadrant arctangent. Returns the angle in (-π, π] of the vector (x, y).
    /// Scale-invariant, so magnitude is normalized down to keep the CORDIC sweep from overflowing.
    /// </summary>
    public static Fixed64 Atan2(Fixed64 y, Fixed64 x)
    {
        long ax = x.Raw;
        long ay = y.Raw;

        if (ax == 0 && ay == 0)
        {
            return Fixed64.Zero;
        }

        // Fold the left half-plane into the right so vectoring converges; correct by ±π after.
        long correction = 0;
        if (ax < 0)
        {
            correction = ay >= 0 ? PiRaw : -PiRaw;
            ax = -ax;
            ay = -ay;
        }

        // Only the ratio matters. Scale both down so x±(y>>i) can never overflow int64.
        long absY = ay >= 0 ? ay : -ay;
        long magnitude = ax >= absY ? ax : absY;
        const long safeLimit = 1L << 59;
        while (magnitude > safeLimit)
        {
            ax >>= 1;
            ay >>= 1;
            magnitude >>= 1;
        }

        // Vectoring mode: drive y to 0, accumulating the rotated angle into z.
        long z = 0;
        for (int i = 0; i < Iterations; i++)
        {
            long dx = ax >> i;
            long dy = ay >> i;
            if (ay >= 0)
            {
                ax += dy;
                ay -= dx;
                z += AtanTable[i];
            }
            else
            {
                ax -= dy;
                ay += dx;
                z -= AtanTable[i];
            }
        }

        return Fixed64.FromRaw(z + correction);
    }

    /// <summary>
    /// Reduce a raw Q32.32 angle to (-π, π] by subtracting the nearest whole number of turns.
    /// The turn constant carries ~½-ULP error, so very large inputs drift slightly — negligible
    /// at the revolution counts this sim reaches, and the caller reduces before angles grow large.
    /// </summary>
    private static long ReduceToPi(long z)
    {
        if (z > -PiRaw && z <= PiRaw)
        {
            return z;
        }

        // k = round(z / 2π)
        long k = z >= 0
            ? (z + TwoPiRaw / 2) / TwoPiRaw
            : (z - TwoPiRaw / 2) / TwoPiRaw;
        return z - k * TwoPiRaw;
    }
}
